In [3]:
import matplotlib.pyplot as plt
import numpy as np
import tensorflow as tf
import os 
from tensorflow.python.framework import ops
ops.reset_default_graph()

C:\Users\Administrator\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [4]:
sess = tf.Session()

In [15]:
#Create data to feed in  
my_array =np.array([[1., 3., 5.,7., 9.],
                  [-2., 0., 2., 4., 6.],
                  [-6., -3., 0., 3., 6.]])
#Duplicate the array for having two inputs
x_vals = np.array([my_array, my_array + 1])
#Declara the placeholder
x_data = tf.placeholder(tf.float32, shape=(3, 5))
#Declare constants for operations
m1 = tf.constant([[1.],[0.],[-1.],[2.],[4.]])
m2 = tf.constant([[2.]])
a1 = tf.constant([[10.]])


In [17]:
#1st Operation Layer  = Multiplication
prod1 = tf.matmul(x_data, m1)
print(sess.run(prod1, feed_dict={x_data: my_array}))



[[46.]
 [28.]
 [24.]]


In [19]:
prod2 = tf.matmul(prod1, m2)
print(sess.run(prod2, feed_dict={x_data:my_array}))

[[92.]
 [56.]
 [48.]]


In [14]:
#3rd Operation Layer = Addition
add1 = tf.add(prod2, a1)
print(sess.run(add1, feed_dict={x_data:my_array}))

[[102.]
 [ 66.]
 [ 58.]]


In [9]:
for x_val in x_vals:
    print(sess.run(add1, feed_dict={x_data: x_val}))

[[102.]
 [ 66.]
 [ 58.]]
[[114.]
 [ 78.]
 [ 70.]]


In [10]:
merged = tf.summary.merge_all(key='summaries')
if not os.path.exists('board_logs/'):
    os.makedirs('board_logs/')
my_writer = tf.summary.FileWriter('board_logs/', sess.graph)    